"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import importlib.util
import os
import sys
from datetime import timedelta
from pathlib import Path

import pymysql

pymysql.version_info = (1, 4, 13, "final", 0)
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================= #
# ******************** Dynamic Config ******************** #
# ================================================= #

try:
    from conf.env import *
except ModuleNotFoundError:
    import logging as _lg
    _lg.getLogger(__name__).warning(
        "conf.env module not found, using default settings (SQLite). "
        "Copy conf/env.example.py to conf/env.py and customize it for production use."
    )
    DATABASE_ENGINE = "django.db.backends.sqlite3"
    DATABASE_NAME = os.path.join(BASE_DIR, "db.sqlite3")
    DATABASE_USER = ""
    DATABASE_PASSWORD = ""
    DATABASE_HOST = ""
    DATABASE_PORT = ""
    TABLE_PREFIX = ""
    REDIS_DB = 0
    CELERY_BROKER_DB = 1
    REDIS_PASSWORD = ""
    REDIS_HOST = "127.0.0.1"
    REDIS_URL = f'redis://:{REDIS_PASSWORD or ""}@{REDIS_HOST}:6379'
    DEBUG = True
    ENABLE_LOGIN_ANALYSIS_LOG = True
    LOGIN_NO_CAPTCHA_AUTH = True
    ALLOWED_HOSTS = ["*"]
    COLUMN_EXCLUDE_APPS = []

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--z8%exyzt7e_%i@1+#1mm=%lb5=^fx_57=1@a+_y7bg5-w%)sm"
# Initialize plugins path into environment variables
PLUGINS_PATH = os.path.join(BASE_DIR, "plugins")
sys.path.insert(0, os.path.join(PLUGINS_PATH))

# taurus_ee 商业版包：物理剥离后客户通过 wheel 安装到 site-packages；
# 开发阶段放在项目根目录，需要显式加进 sys.path.
# 生产环境 wheel 安装后 ROOT_DIR 下不存在 taurus_ee，这行无害（不影响任何东西）。
sys.path.insert(0, str(BASE_DIR.parent))

[
    sys.path.insert(0, os.path.join(PLUGINS_PATH, ele))
    for ele in os.listdir(PLUGINS_PATH)
    if os.path.isdir(os.path.join(PLUGINS_PATH, ele)) and not ele.startswith("__")
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = locals().get("DEBUG", True)
ALLOWED_HOSTS = locals().get("ALLOWED_HOSTS", ["*"])

# Apps to exclude from column permissions
COLUMN_EXCLUDE_APPS = ['channels', 'captcha'] + locals().get("COLUMN_EXCLUDE_APPS", [])

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_comment_migrate",
    "django_extensions",
    "rest_framework",
    "django_filters",
    "corsheaders",  # Register CORS app
    "drf_spectacular",
    "captcha",
    # "channels",  # Removed, use pure asyncio WebSocket instead
    "dvadmin.system",
]

MIDDLEWARE = [
    "dvadmin.utils.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dvadmin.utils.middleware.ApiLoggingMiddleware",
]

ROOT_URLCONF = "application.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "application.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": DATABASE_ENGINE,
        "NAME": DATABASE_NAME,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "HOST": DATABASE_HOST,
        "PORT": DATABASE_PORT,
    }
}
AUTH_USER_MODEL = "system.Users"
USERNAME_FIELD = "username"

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
# # Set Django static file directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Collect static files target directory (must differ from STATICFILES_DIRS)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = "media"  # Directory under project
MEDIA_URL = "/media/"  # Similar to STATIC_URL, specifies the URL users can access files

# With the following code, no need to write {% load staticfiles %}, can reference directly
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder"
)

# ================================================= #
# ******************* CORS Config ******************* #
# ================================================= #

# Allow all configuration
CORS_ORIGIN_ALLOW_ALL = True
# Allow cookies
CORS_ALLOW_CREDENTIALS = True  # Indicates whether backend supports cookie operations during CORS

# ================================================= #
# ******************* HTTPS Security Config *************** #
# ================================================= #
# The following config takes effect automatically when using Nginx reverse proxy
# Determine whether HTTPS is used via X-Forwarded-Proto header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Enabled in production (controlled via environment variables)
SECURE_SSL_REDIRECT = locals().get('ENABLE_HTTPS', False)
SESSION_COOKIE_SECURE = locals().get('ENABLE_HTTPS', False)  # Only transmit session cookie over HTTPS
CSRF_COOKIE_SECURE = locals().get('ENABLE_HTTPS', False)  # Only transmit CSRF cookie over HTTPS

# ===================================================== #
# ******************* WebSocket Config ******************* #
# ===================================================== #
# Removed Channels, switched to pure asyncio WebSocket (websockets library)
# WebSocket server runs independently, not dependent on Django ASGI
WEBSOCKET_ENABLED = True
WEBSOCKET_HOST = os.environ.get('WEBSOCKET_HOST', '0.0.0.0')
WEBSOCKET_PORT = int(os.environ.get('WEBSOCKET_PORT', '8765'))

# ===================================================== #
# ***************** Fernet Encryption Config ******************* #
# ===================================================== #
# Encryption disabled by default, plaintext can be used directly in development
# Must be set to true in production with master key configured
CONFIG_ENCRYPTION_ENABLED = os.environ.get('CONFIG_ENCRYPTION_ENABLED', 'false').lower() == 'true'
CONFIG_ENCRYPTION_KEY = os.environ.get('CONFIG_ENCRYPTION_KEY', '')

# ================================================= #
# ****************** SSL/TLS Config ****************** #
# ================================================= #
# Whether to enable SSL verification (verify server certificate during Supervisor heartbeat requests)
# Disabled by default, use HTTP in development
SUPERVISOR_SSL_VERIFY = os.environ.get('SUPERVISOR_SSL_VERIFY', 'false').lower() == 'true'
# Custom CA certificate path (optional)
SUPERVISOR_SSL_CA_PATH = os.environ.get('SUPERVISOR_SSL_CA_PATH', '')
# Whether to enable request signature verification (enabled by default for API security)
REQUEST_SIGNING_ENABLED = os.environ.get('REQUEST_SIGNING_ENABLED', 'true').lower() == 'true'
# Signature master key (supports encrypted format)
SIGNING_MASTER_KEY = os.environ.get('SIGNING_MASTER_KEY', 'dev-master-key-for-testing-only-not-for-production')


# ================================================= #
# ********************* Logging Config ******************* #
# ================================================= #
# # log ConfigpartBEGIN #
SERVER_LOGS_FILE = os.path.join(BASE_DIR, "logs", "server.log")
ERROR_LOGS_FILE = os.path.join(BASE_DIR, "logs", "error.log")
LOGS_FILE = os.path.join(BASE_DIR, "logs")
if not os.path.exists(os.path.join(BASE_DIR, "logs")):
    os.makedirs(os.path.join(BASE_DIR, "logs"))

# Format:[2020-04-22 23:33:01][micoservice.apps.ready():16] [INFO] This is a sample log entry:
# Format:[Date][Modules.functionName:line number] [Level] Message
STANDARD_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s:%(lineno)d] [%(levelname)s] %(message)s"
)
CONSOLE_LOG_FORMAT = (
    "%(asctime)s %(log_color)s[%(levelname)s]%(reset)s "
    "%(cyan)s[%(name)s.%(funcName)s:%(lineno)d]%(reset)s "
    "%(white)s%(message)s%(reset)s"
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": STANDARD_LOG_FORMAT},
        "console": {
            "()": "colorlog.ColoredFormatter",
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "bold_purple",
            },
        },
        "file": {
            "format": STANDARD_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": SERVER_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 100,  # 100 MB
            "backupCount": 5,  # Max 5 backups
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": ERROR_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 100,  # 100 MB
            "backupCount": 3,  # Max 3 backups
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "console",
        },

    },
    "loggers": {
        "": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
        'django.db.backends': {
            'handlers': ["console", "error", "file"],
            'propagate': False,
            'level': "INFO"
        },
        "uvicorn.error": {
            "level": "INFO",
            "handlers": ["console", "error", "file"],
        },
        "uvicorn.access": {
            "handlers": ["console", "error", "file"],
            "level": "INFO"
        },
    },
}

# ================================================= #
# *************** REST_FRAMEWORK Config *************** #
# ================================================= #

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",  # Datetime format configuration
    "DATE_FORMAT": "%Y-%m-%d",
    "DEFAULT_FILTER_BACKENDS": (
        # 'django_filters.rest_framework.DjangoFilterBackend',
        "dvadmin.utils.filters.CustomDjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "dvadmin.utils.pagination.CustomPagination",  # Custom pagination
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # Only authenticated users can access
    ],
    "EXCEPTION_HANDLER": "dvadmin.utils.exception.CustomExceptionHandler",  # Custom exception handling
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",  # drf-spectacular schema
}
# ================================================= #
# ******************** Authentication Config ******************** #
# ================================================= #

AUTHENTICATION_BACKENDS = ["dvadmin.utils.backends.CustomBackend"]
# ================================================= #
# ****************** simplejwt Config ***************** #
# ================================================= #
SIMPLE_JWT = {
    # Token valid duration
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1440),
    # Token valid duration after refresh
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Set prefix
    "AUTH_HEADER_TYPES": ("JWT", "Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
}

# ====================================#
# ****************drf-spectacular************#
# ====================================#
SPECTACULAR_SETTINGS = {
    "TITLE": "Taurus Ops API",
    "DESCRIPTION": "Taurus Ops API Documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # OTHER SETTINGS
}

# ================================================= #
# **************** Captcha Config  ******************* #
# ================================================= #
CAPTCHA_IMAGE_SIZE = (160, 46)  # Set captcha image size
CAPTCHA_LENGTH = 4  # Character count
CAPTCHA_TIMEOUT = 1  # Timeout (minutes)
CAPTCHA_OUTPUT_FORMAT = "%(image)s %(text_field)s %(hidden_field)s "
CAPTCHA_FONT_SIZE = 36  # Font size
CAPTCHA_FOREGROUND_COLOR = "#64DAAA"  # Foreground color
CAPTCHA_BACKGROUND_COLOR = "#F5F7F4"  # Background color
CAPTCHA_NOISE_FUNCTIONS = (
    "captcha.helpers.noise_arcs",  # line
    # "captcha.helpers.noise_dots",  # .
)
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge' #Letter captcha
CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.math_challenge"  # Arithmetic captcha

# ================================================= #
# ******************** Other Config ******************** #
# ================================================= #

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
API_LOG_ENABLE = True
# API_LOG_METHODS = 'ALL' # ['POST', 'DELETE']
API_LOG_METHODS = ["POST", "UPDATE", "DELETE", "PUT"]  # ['POST', 'DELETE']
API_MODEL_MAP = {
    "/token/": "Login module",
    "/api/login/": "Login module",
    "/api/plugins_market/plugins/": "Plugin market",
}

# ================================================= #
# ****************** CA Certificate Config ******************* #
# ================================================= #
# CA certificate and private key path (used to issue client certificates)
# Note: ca.key must be strictly protected and should not be exposed to clients
CA_CERT_PATH = os.getenv("CA_CERT_PATH", os.path.join(BASE_DIR, "certs", "ca.crt"))
CA_KEY_PATH = os.getenv("CA_KEY_PATH", os.path.join(BASE_DIR, "certs", "ca.key"))

# CRL (Certificate Revocation List) file path
CRL_PATH = os.getenv("CRL_PATH", os.path.join(BASE_DIR, "certs", "crl.pem"))

# ================================================= #
# ****************** SDK Certificate Config ****************** #
# ================================================= #
# SDK client certificate directory (used for gRPC mTLS mutual authentication)
# SDK will look for client certificates (client.crt/client.key) and CA certificate (ca.crt) in this directory
# Can be overridden via env vars TAURUS_CERT_DIR or SDK_CERT_DIR
TAURUS_CERT_DIR = os.getenv("TAURUS_CERT_DIR", os.path.join(BASE_DIR, "certs"))
SDK_CERT_DIR = os.getenv("SDK_CERT_DIR", TAURUS_CERT_DIR)

# ================================================= #
# Executor gRPC Connection Config
# ================================================= #
# SDK connection-level probe timeout: hard timeout (seconds) for initial GetStatus probe RPC.
# 2-3 seconds is usually sufficient for intranet; increase to 5-10s for cross-network/WAN/high-latency environments.
EXECUTOR_CONNECT_TIMEOUT = int(os.getenv("EXECUTOR_CONNECT_TIMEOUT", "5"))

# ================================================= #
# Package directory (for providing installer downloads)
# Config file path, defaults to package_dirs.json under project root
# Can be overridden via env var PACKAGE_DIRS_CONFIG
# 
# JSON file format example:
# {
#   "executor": {
#     "dir": "/path/to/executor",
#     "prefix": "taurus-executor",
#     "ext": ".tar.gz"
#   },
#   "supervisor": {
#     "dir": "/path/to/supervisor",
#     "prefix": "taurus-supervisor",
#     "ext": ""
#   }
# }
#
# Extension method: just modify the JSON file, no code changes needed
import json
PACKAGE_DIRS_CONFIG = os.getenv("PACKAGE_DIRS_CONFIG", os.path.join(BASE_DIR, "package_dirs.json"))
if os.path.exists(PACKAGE_DIRS_CONFIG):
    with open(PACKAGE_DIRS_CONFIG, 'r', encoding='utf-8') as f:
        TAURUS_PACKAGE_DIRS = json.load(f)
else:
    # Default config
    TAURUS_PACKAGE_DIRS = {
        'executor': {
            'dir': os.path.join(BASE_DIR, "app_packages", "taurus-executor"),
            'prefix': 'taurus-executor',
            'ext': '.tar.gz',
        },
        'supervisor': {
            'dir': os.path.join(BASE_DIR, "app_packages", "taurus-supervisor"),
            'prefix': 'taurus-supervisor',
            'ext': '',
        },
        'monitor': {
            'dir': os.path.join(BASE_DIR, "app_packages", "taurus-  monitor"),
            'prefix': 'taurus-monitor',
            'ext': '.tar.gz',
        },
    }

DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_TIMEZONE = "Asia/Shanghai"  # celery timezone issue
# Static page compression
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

ALL_MODELS_OBJECTS = []  # All app models objects

# List to execute after initialization
INITIALIZE_LIST = []
INITIALIZE_RESET_LIST = []
# Table prefix
TABLE_PREFIX = locals().get('TABLE_PREFIX', "")

# Taurus Auth service config
TICKET_AUTH_ENABLED = locals().get('TICKET_AUTH_ENABLED', False)  # Disabled by default
TAURUS_AUTH_URL = locals().get('TAURUS_AUTH_URL', 'http://localhost:8001')
TAURUS_AUTH_JWT_SECRET = locals().get('TAURUS_AUTH_JWT_SECRET', 'your-jwt-secret-key-change-in-production')
TAURUS_AUTH_JWT_EXPIRES_MINUTES = locals().get('TAURUS_AUTH_JWT_EXPIRES_MINUTES', 60)
TAURUS_AUTH_SERVICE_ID = locals().get('TAURUS_AUTH_SERVICE_ID', 'taurus-backend')

# ================================================= #
# ********** Taurus Edition Gate (M1) ********** #
# ================================================= #
# · 取值：'community'(默认)  或  'enterprise'
# · 优先级：环境变量 TAURUS_EDITION  >  conf/env.py 中定义 > 默认 community
# · 切版本仅需改此值，然后 reload 进程即可（loader 有懒加载缓存，测试时用 reset_for_testing()）
TAURUS_EDITION = os.getenv(
    "TAURUS_EDITION",
    locals().get("TAURUS_EDITION", "community"),
).strip().lower()
if TAURUS_EDITION not in ("community", "enterprise"):  # 防御性兜底：非法值回退 community
    import logging as _lg
    _lg.getLogger(__name__).warning(
        "TAURUS_EDITION=%r 非法，已自动回退到 'community'",
        os.getenv("TAURUS_EDITION") or locals().get("TAURUS_EDITION"),
    )
    TAURUS_EDITION = "community"

# · 是否在 DRF Response Header 中暴露 X-Taurus-Edition（便于前端 / 调试识别）
TAURUS_EDITION_EXPOSE_HEADER = True

# · 阶梯定价 Tier 覆盖（仅 EE 场景 License 未加载时使用；M4 后 License 会覆盖掉它）
#   可选值: starter / professional / enterprise / ultimate
TAURUS_EE_DEFAULT_TIER = os.getenv(
    "TAURUS_EE_DEFAULT_TIER",
    locals().get("TAURUS_EE_DEFAULT_TIER", "professional"),
)

# System config
SYSTEM_CONFIG = {}
# Dictionary config
DICTIONARY_CONFIG = {}

# ================================================= #
# ******************** Plugin Config ******************** #
# ================================================= #
# Tenant shared apps
TENANT_SHARED_APPS = []
# Plugin urlpatterns
PLUGINS_URL_PATTERNS = []
# ********** One-click import plugin config start **********
# Example:
# from dvadmin_upgrade_center.settings import *    # Upgrade center
# from dvadmin_celery.settings import *            # celery async tasks
# from dvadmin_third.settings import *            # Third-party user management
# from dvadmin_ak_sk.settings import *            # AK/SK management
# from dvadmin_tenants.settings import *            # Tenant management
# from dvadmin_social_auth.settings import *
# from dvadmin_uniapp.settings import *
# ...
# ********** One-click import plugin config end **********


My_Apps = [
    'taurus',
    # taurus_ee 可选安装：物理剥离后 CE 仓库不含此目录。
    # 条件化让 Django 在 taurus_ee 缺失时仍能正常启动（Thin Wrapper 走 ee_fallback stub）。
    *(["taurus_ee"] if importlib.util.find_spec("taurus_ee") else []),
    'django_celery_beat',
]

INSTALLED_APPS += My_Apps