# Generated by Django 4.2.30 on 2026-08-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="权限码，如 'user:create'",
                        max_length=100,
                        unique=True,
                        verbose_name="权限码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="权限名称，用于显示",
                        max_length=100,
                        verbose_name="权限名称",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="所属模块，用于分组管理",
                        max_length=50,
                        verbose_name="所属模块",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="权限描述",
                        max_length=255,
                        verbose_name="描述",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="是否启用", verbose_name="状态"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限码表",
                "verbose_name_plural": "权限码表",
                "db_table": "taurus_system_permission_code",
                "ordering": ("module", "code"),
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="关联权限码",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_roles",
                        to="system.permissioncode",
                        verbose_name="权限",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="关联角色",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="system.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色权限关联表",
                "verbose_name_plural": "角色权限关联表",
                "db_table": "taurus_system_role_permission",
                "ordering": ("role", "permission"),
                "unique_together": {("role", "permission")},
            },
        ),
    ]
