# Generated by Django 4.2.30 on 2026-08-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taurus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opsexecution",
            name="use_shell",
            field=models.BooleanField(default=True, verbose_name="使用Shell模式"),
        ),
    ]
