# Generated by Django 4.2.30 on 2026-08-03 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taurus", "0003_ops_execution_approval"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="opsexecutionapproval",
            new_name="taurus_ops__status_2a3453_idx",
            old_name="taurus_ops_status_idx",
        ),
        migrations.RenameIndex(
            model_name="opsexecutionapproval",
            new_name="taurus_ops__submitt_0b1460_idx",
            old_name="taurus_ops_submit_idx",
        ),
        migrations.RenameIndex(
            model_name="opsexecutionapproval",
            new_name="taurus_ops__batch_i_cad1dd_idx",
            old_name="taurus_ops_batch_idx",
        ),
        migrations.RemoveField(
            model_name="opsexecutionapproval",
            name="creator_name",
        ),
        migrations.RemoveField(
            model_name="opsexecutionapproval",
            name="modifier_name",
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="dept_belong_id",
            field=models.CharField(
                blank=True,
                help_text="数据归属部门",
                max_length=255,
                null=True,
                verbose_name="数据归属部门",
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="create_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="创建时间",
                null=True,
                verbose_name="创建时间",
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="creator",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="描述",
                max_length=255,
                null=True,
                verbose_name="描述",
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="id",
            field=models.BigAutoField(
                help_text="Id", primary_key=True, serialize=False, verbose_name="Id"
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="modifier",
            field=models.CharField(
                blank=True,
                help_text="修改人",
                max_length=255,
                null=True,
                verbose_name="修改人",
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="update_datetime",
            field=models.DateTimeField(
                auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间"
            ),
        ),
    ]
