# Generated by Django 4.2.30 on 2026-08-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taurus", "0005_add_exec_strategy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="opsexecution",
            name="auto_notify",
            field=models.BooleanField(default=False, verbose_name="是否自动通知"),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="concurrent",
            field=models.IntegerField(default=10, verbose_name="并发数"),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="exec_mode",
            field=models.CharField(
                choices=[
                    ("serial", "串行执行"),
                    ("parallel", "并行执行"),
                    ("pilot", "灰度放量"),
                ],
                default="parallel",
                max_length=20,
                verbose_name="执行模式",
            ),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="fail_strategy",
            field=models.CharField(
                choices=[
                    ("stop", "失败终止全部"),
                    ("continue", "跳过失败继续"),
                    ("abort", "中止(兼容旧)"),
                ],
                default="continue",
                max_length=20,
                verbose_name="失败策略",
            ),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="need_audit",
            field=models.BooleanField(default=False, verbose_name="是否需审批"),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="pilot_count",
            field=models.IntegerField(default=2, verbose_name="灰度验证主机数"),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="pilot_success_rate",
            field=models.IntegerField(default=100, verbose_name="灰度成功阈值(%)"),
        ),
        migrations.AddField(
            model_name="workflow",
            name="graph_definition",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="DAG 草稿（nodes + edges，编辑态）",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="graph_version",
            field=models.PositiveIntegerField(
                default=0, verbose_name="草稿版本号（乐观锁）"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="workflow_mode",
            field=models.CharField(
                choices=[
                    ("linear", "线性模式（旧版，按 step_order）"),
                    ("dag", "DAG 模式（新版，走 workflow.engine）"),
                ],
                db_index=True,
                default="linear",
                max_length=16,
                verbose_name="执行模式",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="current_node_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="当前执行节点 key（DAG 模式用；线性模式仍用 current_step）",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="fail_strategy",
            field=models.CharField(
                choices=[
                    ("fail_fast", "失败即终止（默认）"),
                    ("continue", "失败继续执行兄弟节点"),
                ],
                default="fail_fast",
                max_length=16,
                verbose_name="失败策略",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="trigger_params",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="本次触发参数（渲染时参与插值）"
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "手动触发"),
                    ("schedule", "定时任务"),
                    ("api", "API 调用"),
                ],
                db_index=True,
                default="manual",
                max_length=16,
                verbose_name="触发类型",
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="current_step",
            field=models.IntegerField(
                default=0, verbose_name="当前执行步骤（linear 模式用）"
            ),
        ),
        migrations.CreateModel(
            name="WorkflowDAGVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=1,
                        verbose_name="版本号（自增，按工作流维度内部自增）",
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        default=dict, verbose_name="DAG 冻结定义（nodes + edges）"
                    ),
                ),
                (
                    "global_envs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="全局环境变量快照"
                    ),
                ),
                (
                    "release_note",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="发布备注"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dag_versions",
                        to="taurus.workflow",
                        verbose_name="所属工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流 DAG 发布版本",
                "db_table": "taurus_workflow_dag_version",
                "ordering": ("-workflow_id", "-version"),
            },
        ),
        migrations.AddField(
            model_name="workflow",
            name="dag_published_version",
            field=models.ForeignKey(
                blank=True,
                db_column="dag_published_version_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="taurus.workflowdagversion",
                verbose_name="当前发布版本",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="dag_version",
            field=models.ForeignKey(
                blank=True,
                db_column="dag_version_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="taurus.workflowdagversion",
                verbose_name="DAG 发布版本快照",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowNodeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "node_key",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        verbose_name="节点 key（DAG 内唯一）",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="适配器 node_type"
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="节点展示名（执行时快照）",
                    ),
                ),
                (
                    "host_id",
                    models.CharField(
                        db_index=True,
                        default="__NO_HOST__",
                        max_length=64,
                        verbose_name="主机 ID (UUID) 或 __NO_HOST__",
                    ),
                ),
                (
                    "dispatch_id",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="幂等键（适配器 dispatch 入参）",
                    ),
                ),
                (
                    "attempt_no",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="第几次尝试（从 1 开始）"
                    ),
                ),
                (
                    "rendered_params",
                    models.JSONField(
                        default=dict, verbose_name="渲染后的节点配置（含插值结果）"
                    ),
                ),
                (
                    "secrets_mask",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="需脱敏的 JSON Pointer 列表（view_masked 用）",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待执行"),
                            (1, "执行中"),
                            (2, "成功"),
                            (3, "失败"),
                            (4, "跳过"),
                            (5, "已取消"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="执行状态（0~5 全局常量）",
                    ),
                ),
                (
                    "exit_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="进程退出码（无则 null）"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="错误信息（含 E0xxx/E2xxx 前缀）",
                    ),
                ),
                (
                    "adapter_state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="适配器内部状态"
                    ),
                ),
                (
                    "output",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="执行输出（上游可 ${node_key.output.xxx} 引用）",
                    ),
                ),
                (
                    "output_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="附件引用列表（如采集的文件 manifest）",
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="入队时间"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="首次 dispatch 时间",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="到达终态时间",
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="实际执行耗时（毫秒，不含排队）",
                    ),
                ),
                (
                    "timeout_sec",
                    models.IntegerField(
                        default=0,
                        help_text="0 = 使用全局配置",
                        verbose_name="配置超时秒数",
                    ),
                ),
                (
                    "poll_count",
                    models.IntegerField(
                        default=0, verbose_name="poll 调用次数（监控用，避免无限轮询）"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="触发用户 ID"
                    ),
                ),
                (
                    "fail_strategy",
                    models.CharField(
                        choices=[
                            ("fail_fast", "失败即终止（默认）"),
                            ("continue", "失败继续执行兄弟节点"),
                        ],
                        default="fail_fast",
                        max_length=16,
                        verbose_name="该节点的失败策略",
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=8,
                        null=True,
                        verbose_name="最近一次错误码前缀（如 E2401）",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "dag_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="node_executions",
                        to="taurus.workflowdagversion",
                        verbose_name="DAG 版本快照",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_executions",
                        to="taurus.workflowexecution",
                        verbose_name="所属执行实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流节点执行实例",
                "db_table": "taurus_workflow_node_execution",
                "ordering": ("execution_id", "node_key", "-attempt_no"),
                "indexes": [
                    models.Index(
                        fields=["execution", "status"], name="idx_node_exec_status"
                    ),
                    models.Index(
                        fields=["node_type", "status"], name="idx_node_ntype_status"
                    ),
                    models.Index(
                        fields=["dag_version", "node_key"], name="idx_node_dagv_key"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="workflownodeexecution",
            constraint=models.UniqueConstraint(
                fields=("execution", "node_key", "host_id", "attempt_no"),
                name="uniq_node_exec_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowdagversion",
            constraint=models.UniqueConstraint(
                fields=("workflow", "version"), name="uniq_wf_dag_version_pair"
            ),
        ),
    ]
