# Generated by Django 4.2.30 on 2026-08-10 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taurus", "0006_opsexecution_auto_notify_opsexecution_concurrent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowApprovalInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "workflow_version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="流程版本"
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="规则名称快照"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("cancelled", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="流程状态",
                    ),
                ),
                (
                    "current_node_index",
                    models.IntegerField(default=0, verbose_name="当前审核节点索引"),
                ),
                (
                    "submitter_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="提交人名称"
                    ),
                ),
                (
                    "submit_desc",
                    models.TextField(blank=True, null=True, verbose_name="提交说明"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="风险级别"
                    ),
                ),
                (
                    "risk_points",
                    models.JSONField(
                        blank=True, default=list, verbose_name="风险点列表快照"
                    ),
                ),
                (
                    "finish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流审核流程实例",
                "db_table": "taurus_workflow_approval_instance",
                "ordering": ["-create_datetime"],
            },
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="approval_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("any", "或签（任一人通过即可）"),
                    ("all", "会签（所有人必须通过）"),
                ],
                max_length=10,
                null=True,
                verbose_name="审核模式（快照）",
            ),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="approver_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON: [user_id, ...]",
                verbose_name="或签审核人ID列表（快照）",
            ),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="countersign_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON: [user_id, ...]",
                verbose_name="会签审核人ID列表（快照）",
            ),
        ),
        migrations.AddField(
            model_name="opsexecution",
            name="submit_desc",
            field=models.TextField(
                blank=True, null=True, verbose_name="审批提交说明（快照）"
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="approval_mode",
            field=models.CharField(
                choices=[
                    ("any", "或签（任一人通过即可）"),
                    ("all", "会签（所有人必须通过）"),
                ],
                default="any",
                max_length=10,
                verbose_name="多人审核模式",
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="approval_records",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON: [{user_id, username, action(approve/reject/delegate/add_sign), reason, operate_time, ...}]",
                verbose_name="审核动作记录",
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="auto_notify",
            field=models.BooleanField(default=False, verbose_name="完成后是否自动通知"),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="candidate_approvers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON: [{user_id, username, name}, ...]，优先级高于单个 approver 字段",
                verbose_name="候选审核人列表",
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="command",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="命令"
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="execution_type",
            field=models.CharField(
                choices=[
                    ("command", "命令"),
                    ("script", "脚本"),
                    ("upload", "文件上传"),
                    ("download", "文件下载"),
                ],
                default="script",
                max_length=20,
                verbose_name="执行类型",
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="fail_strategy",
            field=models.CharField(
                choices=[("stop", "失败终止全部"), ("continue", "跳过失败继续")],
                default="continue",
                max_length=20,
                verbose_name="失败策略",
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="pilot_count",
            field=models.IntegerField(default=2, verbose_name="灰度验证主机数"),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="pilot_success_rate",
            field=models.IntegerField(default=100, verbose_name="灰度成功阈值(%)"),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="use_shell",
            field=models.BooleanField(
                default=True, verbose_name="使用Shell模式（命令执行）"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="dag_version",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="taurus.workflowdagversion",
                verbose_name="DAG 版本（空=使用当前发布版）",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="auth_type",
            field=models.CharField(
                choices=[("私有", "私有"), ("公共", "公共")],
                default="私有",
                max_length=20,
                verbose_name="授权类型",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="exec_count",
            field=models.IntegerField(default=0, verbose_name="执行次数"),
        ),
        migrations.AddField(
            model_name="workflow",
            name="last_exec_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后执行时间"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="need_audit",
            field=models.BooleanField(default=False, verbose_name="是否需审批"),
        ),
        migrations.AlterField(
            model_name="opsexecution",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "待执行"),
                    (1, "执行中"),
                    (2, "已完成"),
                    (3, "失败"),
                    (4, "中断"),
                    (5, "审批中"),
                    (6, "审批驳回"),
                ],
                default=0,
                verbose_name="执行状态",
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="approve_reason",
            field=models.TextField(blank=True, null=True, verbose_name="最终审批意见"),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="approve_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最终审批时间"
            ),
        ),
        migrations.AlterField(
            model_name="opsexecutionapproval",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_exec_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人（最终通过/驳回操作人）",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="status",
            field=models.IntegerField(
                choices=[(0, "正常启用"), (1, "已禁用"), (2, "待审批"), (3, "已归档")],
                default=0,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="dag_version",
            field=models.ForeignKey(
                blank=True,
                db_column="dag_version_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="taurus.workflowdagversion",
                verbose_name="DAG 发布版本快照",
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "手动触发"),
                    ("schedule", "定时任务"),
                    ("api", "API 调用"),
                    ("dryrun", "试运行"),
                ],
                db_index=True,
                default="manual",
                max_length=16,
                verbose_name="触发类型",
            ),
        ),
        migrations.AlterField(
            model_name="workflownodeexecution",
            name="dag_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node_executions",
                to="taurus.workflowdagversion",
                verbose_name="DAG 版本快照",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "category_code",
                    models.CharField(
                        blank=True,
                        help_text="前端友好标识，如 deploy/inspect 等",
                        max_length=64,
                        null=True,
                        verbose_name="分类编码",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="系统内置分类不允许删除",
                        verbose_name="系统内置",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="taurus.workflowcategory",
                        verbose_name="父分类",
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="该分类下的流程提交审核时，从这些审核人中分配审核任务",
                        related_name="reviewable_workflow_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程分类",
                "verbose_name_plural": "流程分类",
                "db_table": "taurus_workflow_category",
                "ordering": ("sort", "id"),
            },
        ),
        migrations.CreateModel(
            name="WorkflowApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "condition_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='\n        组内条件为AND关系，组之间为OR关系（任一条件组命中即规则命中）。\n        每组支持的条件字段（留空表示不限制）：\n        - category_ids: [1, 2, 3]         # 分类ID列表（包含子分类）\n        - workflow_modes: ["dag", "linear"]  # 流程模式列表\n        - risk_levels: ["high", "medium"] # 风险等级列表\n        - min_risk_points: 3              # 最少风险点数（大于等于）\n        - auth_types: ["公共", "私有"]    # 授权类型列表\n        - submitter_roles: ["dev"]        # 提交人角色编码列表\n        示例: [{"category_ids": [5], "risk_levels": ["high"]}, {"workflow_modes": ["dag"]}]\n        ',
                        verbose_name="条件组列表",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="数字越小优先级越高，按优先级从上往下匹配",
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流审核规则",
                "db_table": "taurus_workflow_approval_rule",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowApprovalNodeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "node_name",
                    models.CharField(max_length=100, verbose_name="节点名称"),
                ),
                (
                    "approver_type",
                    models.CharField(max_length=30, verbose_name="审核人类型"),
                ),
                (
                    "approver_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="审核人配置快照"
                    ),
                ),
                (
                    "approval_mode",
                    models.CharField(max_length=10, verbose_name="审核模式"),
                ),
                ("step_order", models.IntegerField(verbose_name="节点顺序")),
                (
                    "candidate_approvers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="格式: [{user_id, username, name}]",
                        verbose_name="候选审核人列表",
                    ),
                ),
                (
                    "approval_records",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="格式: [{user_id, username, action: approve/reject/delegate/add_sign, reason, operate_time, target_user}]",
                        verbose_name="审核操作记录",
                    ),
                ),
                (
                    "delegate_records",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="格式: [{from_user_id, from_username, to_user_id, to_username, reason, operate_time}]",
                        verbose_name="转审记录",
                    ),
                ),
                (
                    "add_sign_records",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="格式: [{operator_id, operator_username, added_user_ids, reason, operate_time}]",
                        verbose_name="加签记录",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="节点状态",
                    ),
                ),
                (
                    "finish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_executions",
                        to="taurus.workflowapprovalinstance",
                        verbose_name="所属流程实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流审核节点执行记录",
                "db_table": "taurus_workflow_approval_node_exec",
                "ordering": ["step_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowApprovalNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        help_text="如：一级审核、安全审核、DBA审核等",
                        max_length=100,
                        verbose_name="节点名称",
                    ),
                ),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("category_reviewer", "分类审核人"),
                            ("specific_users", "指定用户"),
                            ("role", "指定角色"),
                            ("submitter_manager", "提交人主管"),
                        ],
                        max_length=30,
                        verbose_name="审核人类型",
                    ),
                ),
                (
                    "approver_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        category_reviewer: {}                         # 无需额外配置\n        specific_users: {"user_ids": [1, 2, 3]}       # 指定用户ID列表\n        role: {"role_codes": ["dba", "security"]}     # 指定角色编码列表\n        submitter_manager: {"levels": 1}              # 向上几级主管（1=直属）\n        ',
                        verbose_name="审核人配置",
                    ),
                ),
                (
                    "approval_mode",
                    models.CharField(
                        choices=[("any", "或签"), ("all", "会签"), ("first", "先签")],
                        default="any",
                        max_length=10,
                        verbose_name="审核模式",
                    ),
                ),
                (
                    "step_order",
                    models.IntegerField(
                        default=1, help_text="数字越小越先执行", verbose_name="执行顺序"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="taurus.workflowapprovalrule",
                        verbose_name="所属规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流审核节点",
                "db_table": "taurus_workflow_approval_node",
                "ordering": ["step_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="workflowapprovalinstance",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taurus.workflowapprovalrule",
                verbose_name="命中的规则",
            ),
        ),
        migrations.AddField(
            model_name="workflowapprovalinstance",
            name="submitter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_submitted_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交人",
            ),
        ),
        migrations.AddField(
            model_name="workflowapprovalinstance",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_instances",
                to="taurus.workflow",
                verbose_name="工作流",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflows",
                to="taurus.workflowcategory",
                verbose_name="流程分类",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowApprove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "workflow_version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="流程版本"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低危"), ("medium", "中危"), ("high", "高危")],
                        default="low",
                        max_length=20,
                        verbose_name="风险级别",
                    ),
                ),
                (
                    "risk_points",
                    models.JSONField(
                        blank=True, default=list, verbose_name="风险点列表"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "submitter_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="提交人名称"
                    ),
                ),
                (
                    "submit_desc",
                    models.TextField(blank=True, null=True, verbose_name="提交说明"),
                ),
                (
                    "approver_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="审批人名称"
                    ),
                ),
                (
                    "approve_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "approve_reason",
                    models.TextField(blank=True, null=True, verbose_name="审批理由"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_approvals_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_approvals_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="taurus.workflow",
                        verbose_name="工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业编排审批记录",
                "db_table": "taurus_workflow_approve",
                "ordering": ["-create_datetime"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "status"],
                        name="taurus_work_workflo_145317_idx",
                    ),
                    models.Index(
                        fields=["submitter"], name="taurus_work_submitt_7593df_idx"
                    ),
                    models.Index(
                        fields=["approver"], name="taurus_work_approve_1576ae_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workflowapprovalrule",
            index=models.Index(
                fields=["is_active", "priority"], name="taurus_work_is_acti_f02032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapprovalnodeexecution",
            index=models.Index(
                fields=["instance", "step_order"], name="taurus_work_instanc_e22edc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapprovalnodeexecution",
            index=models.Index(fields=["status"], name="taurus_work_status_32dc53_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowapprovalnode",
            index=models.Index(
                fields=["rule", "step_order"], name="taurus_work_rule_id_44cfaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapprovalinstance",
            index=models.Index(
                fields=["workflow", "status"], name="taurus_work_workflo_6b22a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapprovalinstance",
            index=models.Index(
                fields=["submitter"], name="taurus_work_submitt_ed4c12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapprovalinstance",
            index=models.Index(fields=["status"], name="taurus_work_status_a4d6ea_idx"),
        ),
    ]
