# Generated by Django 4.2.30 on 2026-08-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taurus", "0007_workflowapprovalinstance_opsexecution_approval_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("script", "脚本"), ("workflow", "工作流")],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        max_length=100, verbose_name="资源ID(脚本ID/工作流ID)"
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="分享令牌(URL参数)"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list, verbose_name="权限编码列表(JSON数组)"
                    ),
                ),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间(None=永久)"
                    ),
                ),
                (
                    "max_access_count",
                    models.IntegerField(
                        default=0, verbose_name="最大访问次数(0=不限制)"
                    ),
                ),
                (
                    "current_access_count",
                    models.IntegerField(default=0, verbose_name="当前已访问次数"),
                ),
                (
                    "access_scope",
                    models.CharField(
                        choices=[
                            ("authenticated", "仅登录用户可访问"),
                            ("anyone", "任何人(知道链接即可，无需登录)"),
                        ],
                        default="authenticated",
                        max_length=20,
                        verbose_name="访问范围",
                    ),
                ),
                (
                    "bind_subject_type",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="绑定主体类型(user/role/dept)",
                    ),
                ),
                (
                    "bind_subject_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="绑定主体ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="是否启用(可手动撤销)"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_links_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享链接",
                "db_table": "taurus_share_link",
                "ordering": ["-create_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ScriptSharePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("user", "用户"), ("role", "角色"), ("dept", "部门")],
                        default="user",
                        max_length=20,
                        verbose_name="主体类型",
                    ),
                ),
                (
                    "subject_id",
                    models.CharField(
                        max_length=100, verbose_name="主体ID(用户ID/角色ID/部门ID)"
                    ),
                ),
                (
                    "subject_name_cache",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="主体名称缓存(避免多次join查询)",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list, verbose_name="权限编码列表(JSON数组)"
                    ),
                ),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间(None=永久)"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "grant_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="script_share_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授权人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_permissions",
                        to="taurus.script",
                        verbose_name="脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本分享权限",
                "db_table": "taurus_script_share_permission",
            },
        ),
        migrations.CreateModel(
            name="WorkflowSharePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("user", "用户"), ("role", "角色"), ("dept", "部门")],
                        default="user",
                        max_length=20,
                        verbose_name="主体类型",
                    ),
                ),
                ("subject_id", models.CharField(max_length=100, verbose_name="主体ID")),
                (
                    "subject_name_cache",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="主体名称缓存"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list, verbose_name="权限编码列表(JSON数组)"
                    ),
                ),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间(None=永久)"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "grant_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_share_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授权人",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_permissions",
                        to="taurus.workflow",
                        verbose_name="工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流分享权限",
                "db_table": "taurus_workflow_share_permission",
                "indexes": [
                    models.Index(
                        fields=["subject_type", "subject_id"],
                        name="taurus_work_subject_58652f_idx",
                    ),
                    models.Index(
                        fields=["expire_time"], name="taurus_work_expire__ca4fc7_idx"
                    ),
                ],
                "unique_together": {("workflow", "subject_type", "subject_id")},
            },
        ),
        migrations.CreateModel(
            name="SharePermissionDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("script", "脚本"), ("workflow", "工作流")],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "perm_code",
                    models.CharField(max_length=100, verbose_name="权限编码"),
                ),
                (
                    "perm_name",
                    models.CharField(max_length=100, verbose_name="权限名称"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("view", "查看类"),
                            ("edit", "编辑类"),
                            ("execute", "执行类"),
                            ("manage", "管理类"),
                        ],
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="说明"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享权限定义",
                "db_table": "taurus_share_permission_def",
                "ordering": ("resource_type", "category", "sort"),
                "unique_together": {("resource_type", "perm_code")},
            },
        ),
        migrations.CreateModel(
            name="ShareLinkAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=255,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=255,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=255,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "client_ip",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="客户端IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="浏览器UA"
                    ),
                ),
                (
                    "access_success",
                    models.BooleanField(
                        default=True, verbose_name="是否成功(过期/超次数则失败)"
                    ),
                ),
                (
                    "fail_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="失败原因"
                    ),
                ),
                (
                    "access_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_link_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="访问用户(未登录则为空)",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="taurus.sharelink",
                        verbose_name="所属分享链接",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享链接访问日志",
                "db_table": "taurus_share_link_access_log",
                "ordering": ["-create_datetime"],
                "indexes": [
                    models.Index(
                        fields=["share_link", "create_datetime"],
                        name="taurus_shar_share_l_fb6225_idx",
                    ),
                    models.Index(
                        fields=["access_user"], name="taurus_shar_access__c99e63_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["share_token"], name="taurus_shar_share_t_9b8379_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="taurus_shar_resourc_ae32ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["expire_time"], name="taurus_shar_expire__789ad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["is_active"], name="taurus_shar_is_acti_90b11b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scriptsharepermission",
            index=models.Index(
                fields=["subject_type", "subject_id"],
                name="taurus_scri_subject_4e6802_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scriptsharepermission",
            index=models.Index(
                fields=["expire_time"], name="taurus_scri_expire__f994ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scriptsharepermission",
            unique_together={("script", "subject_type", "subject_id")},
        ),
    ]
