# Generated by Django 4.2.30 on 2026-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taurus", "0008_sharelink_scriptsharepermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="custom_approver_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="保存工作流时可手动指定审核用户ID列表，提交审核时若无匹配规则则按此创建单级指定用户审核；非空时即使 need_audit=False 但可见性=公共也优先使用此审核人",
                verbose_name="自定义审核人ID列表",
            ),
        ),
    ]
