# Generated by Django 4.2.30 on 2026-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taurus", "0011_workflow_last_exec_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="fail_strategy",
            field=models.CharField(
                choices=[("stop", "终止流程"), ("continue", "继续执行")],
                default="stop",
                help_text="全局失败策略：终止流程或继续执行",
                max_length=20,
                verbose_name="失败策略",
            ),
        ),
    ]