# Generated by Django 4.2.30 on 2026-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taurus", "0012_workflow_fail_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="cron_expression",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cron 表达式"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="has_schedule",
            field=models.BooleanField(default=False, verbose_name="是否启用定时触发"),
        ),
        migrations.AddField(
            model_name="workflow",
            name="interval_seconds",
            field=models.IntegerField(blank=True, null=True, verbose_name="间隔秒数"),
        ),
        migrations.AddField(
            model_name="workflow",
            name="run_once_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="一次性执行时间"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="schedule_enabled",
            field=models.BooleanField(default=True, verbose_name="定时是否启用"),
        ),
        migrations.AddField(
            model_name="workflow",
            name="schedule_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cron", "Cron 表达式"),
                    ("interval", "固定间隔"),
                    ("once", "一次性"),
                ],
                max_length=20,
                null=True,
                verbose_name="定时类型",
            ),
        ),
    ]
