# Generated by Django 4.2.30 on 2026-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taurus", "0013_workflow_missing_schedule_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="related_desc",
            field=models.TextField(
                blank=True,
                help_text="脚本描述/工作流描述/节点描述",
                null=True,
                verbose_name="关联描述",
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="related_name",
            field=models.CharField(
                blank=True,
                help_text="脚本名/工作流名/命令摘要",
                max_length=200,
                null=True,
                verbose_name="关联名称",
            ),
        ),
        migrations.AddField(
            model_name="opsexecutionapproval",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("workflow", "工作流审核"),
                    ("script", "脚本执行"),
                    ("command", "命令执行"),
                ],
                default="script",
                max_length=20,
                verbose_name="审核来源类型",
            ),
        ),
    ]
